CREATE OR REPLACE PACKAGE PLACE_PACKAGE AS
  TYPE T_PLACE IS RECORD (
    place_id NUMBER,
    address VARCHAR2(60),
    room_number NUMBER,
    schedule VARCHAR2(11)
  );

  TYPE T_PLACE_TABLE IS TABLE OF T_PLACE;

  FUNCTION GET_PLACE(P_ID IN Place.place_id%TYPE)
    RETURN T_PLACE_TABLE PIPELINED;
  FUNCTION GET_PLACES
    RETURN T_PLACE_TABLE PIPELINED;
END;

CREATE OR REPLACE PACKAGE BODY PLACE_PACKAGE AS
  FUNCTION GET_PLACE(P_ID IN Place.place_id%type)
    RETURN T_PLACE_TABLE PIPELINED AS
    CURSOR MY_CUR IS
      SELECT *
      FROM Place
      WHERE PLACE_ID = P_ID;
    BEGIN
      FOR CURR IN MY_CUR
      LOOP
        PIPE ROW (CURR);
      end loop;
    END;

  FUNCTION GET_PLACES
    RETURN T_PLACE_TABLE PIPELINED AS
    CURSOR MY_CURSOR IS
      SELECT *
      FROM Place;
    BEGIN
      FOR REC IN MY_CURSOR
      LOOP
        PIPE ROW (REC);
      END LOOP;
    END;
END PLACE_PACKAGE;
  /

select * 
from table (PLACE_PACKAGE.GET_PLACE(2));
